// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Symbol int32

const (
	Symbol_Clubs    Symbol = 0
	Symbol_Diamonds Symbol = 1
	Symbol_Hearts   Symbol = 2
	Symbol_Spades   Symbol = 3
)

// Enum value maps for Symbol.
var (
	Symbol_name = map[int32]string{
		0: "Clubs",
		1: "Diamonds",
		2: "Hearts",
		3: "Spades",
	}
	Symbol_value = map[string]int32{
		"Clubs":    0,
		"Diamonds": 1,
		"Hearts":   2,
		"Spades":   3,
	}
)

func (x Symbol) Enum() *Symbol {
	p := new(Symbol)
	*p = x
	return p
}

func (x Symbol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Symbol) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (Symbol) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x Symbol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Symbol.Descriptor instead.
func (Symbol) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value  int32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Symbol Symbol  `protobuf:"varint,3,opt,name=symbol,proto3,enum=Symbol" json:"symbol,omitempty"`
	Owner  *string `protobuf:"bytes,4,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Card) GetSymbol() Symbol {
	if x != nil {
		return x.Symbol
	}
	return Symbol_Clubs
}

func (x *Card) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Set) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type HiddenSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumOfCards int32 `protobuf:"varint,1,opt,name=numOfCards,proto3" json:"numOfCards,omitempty"`
}

func (x *HiddenSet) Reset() {
	*x = HiddenSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiddenSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenSet) ProtoMessage() {}

func (x *HiddenSet) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenSet.ProtoReflect.Descriptor instead.
func (*HiddenSet) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *HiddenSet) GetNumOfCards() int32 {
	if x != nil {
		return x.NumOfCards
	}
	return 0
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandSet    *HiddenSet `protobuf:"bytes,1,opt,name=handSet,proto3" json:"handSet,omitempty"`
	PlayedSets []*Set     `protobuf:"bytes,2,rep,name=playedSets,proto3" json:"playedSets,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInfo) GetHandSet() *HiddenSet {
	if x != nil {
		return x.HandSet
	}
	return nil
}

func (x *PlayerInfo) GetPlayedSets() []*Set {
	if x != nil {
		return x.PlayedSets
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	// Types that are assignable to Action:
	//
	//	*Action_Start
	//	*Action_Draw
	//	*Action_DrawFolded
	//	*Action_Fold
	//	*Action_PlaySet
	//	*Action_PlaySingleCard
	Action isAction_Action `protobuf_oneof:"action"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Action) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (m *Action) GetAction() isAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Action) GetStart() *Start {
	if x, ok := x.GetAction().(*Action_Start); ok {
		return x.Start
	}
	return nil
}

func (x *Action) GetDraw() *Draw {
	if x, ok := x.GetAction().(*Action_Draw); ok {
		return x.Draw
	}
	return nil
}

func (x *Action) GetDrawFolded() *DrawFolded {
	if x, ok := x.GetAction().(*Action_DrawFolded); ok {
		return x.DrawFolded
	}
	return nil
}

func (x *Action) GetFold() *Fold {
	if x, ok := x.GetAction().(*Action_Fold); ok {
		return x.Fold
	}
	return nil
}

func (x *Action) GetPlaySet() *PlaySet {
	if x, ok := x.GetAction().(*Action_PlaySet); ok {
		return x.PlaySet
	}
	return nil
}

func (x *Action) GetPlaySingleCard() *PlaySingleCard {
	if x, ok := x.GetAction().(*Action_PlaySingleCard); ok {
		return x.PlaySingleCard
	}
	return nil
}

type isAction_Action interface {
	isAction_Action()
}

type Action_Start struct {
	Start *Start `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type Action_Draw struct {
	Draw *Draw `protobuf:"bytes,3,opt,name=draw,proto3,oneof"`
}

type Action_DrawFolded struct {
	DrawFolded *DrawFolded `protobuf:"bytes,4,opt,name=drawFolded,proto3,oneof"`
}

type Action_Fold struct {
	Fold *Fold `protobuf:"bytes,5,opt,name=fold,proto3,oneof"`
}

type Action_PlaySet struct {
	PlaySet *PlaySet `protobuf:"bytes,6,opt,name=playSet,proto3,oneof"`
}

type Action_PlaySingleCard struct {
	PlaySingleCard *PlaySingleCard `protobuf:"bytes,7,opt,name=playSingleCard,proto3,oneof"`
}

func (*Action_Start) isAction_Action() {}

func (*Action_Draw) isAction_Action() {}

func (*Action_DrawFolded) isAction_Action() {}

func (*Action_Fold) isAction_Action() {}

func (*Action_PlaySet) isAction_Action() {}

func (*Action_PlaySingleCard) isAction_Action() {}

type Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start) Reset() {
	*x = Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

type Draw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Draw) Reset() {
	*x = Draw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Draw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Draw) ProtoMessage() {}

func (x *Draw) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Draw.ProtoReflect.Descriptor instead.
func (*Draw) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

type DrawFolded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumOfCards int32 `protobuf:"varint,1,opt,name=numOfCards,proto3" json:"numOfCards,omitempty"`
}

func (x *DrawFolded) Reset() {
	*x = DrawFolded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawFolded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawFolded) ProtoMessage() {}

func (x *DrawFolded) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawFolded.ProtoReflect.Descriptor instead.
func (*DrawFolded) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DrawFolded) GetNumOfCards() int32 {
	if x != nil {
		return x.NumOfCards
	}
	return 0
}

type Fold struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *Fold) Reset() {
	*x = Fold{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fold) ProtoMessage() {}

func (x *Fold) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fold.ProtoReflect.Descriptor instead.
func (*Fold) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Fold) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type PlaySet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards *Set `protobuf:"bytes,1,opt,name=cards,proto3" json:"cards,omitempty"`
}

func (x *PlaySet) Reset() {
	*x = PlaySet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySet) ProtoMessage() {}

func (x *PlaySet) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySet.ProtoReflect.Descriptor instead.
func (*PlaySet) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *PlaySet) GetCards() *Set {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PlaySingleCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumOfSet   int32  `protobuf:"varint,2,opt,name=numOfSet,proto3" json:"numOfSet,omitempty"`
	Card       *Card  `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	JokerOnLow *bool  `protobuf:"varint,4,opt,name=jokerOnLow,proto3,oneof" json:"jokerOnLow,omitempty"`
}

func (x *PlaySingleCard) Reset() {
	*x = PlaySingleCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaySingleCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySingleCard) ProtoMessage() {}

func (x *PlaySingleCard) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySingleCard.ProtoReflect.Descriptor instead.
func (*PlaySingleCard) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PlaySingleCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaySingleCard) GetNumOfSet() int32 {
	if x != nil {
		return x.NumOfSet
	}
	return 0
}

func (x *PlaySingleCard) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PlaySingleCard) GetJokerOnLow() bool {
	if x != nil && x.JokerOnLow != nil {
		return *x.JokerOnLow
	}
	return false
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrawSet       *HiddenSet             `protobuf:"bytes,1,opt,name=drawSet,proto3" json:"drawSet,omitempty"`
	FoldSet       *Set                   `protobuf:"bytes,2,opt,name=foldSet,proto3" json:"foldSet,omitempty"`
	HandSet       *Set                   `protobuf:"bytes,3,opt,name=handSet,proto3" json:"handSet,omitempty"`
	PlayerInfos   map[string]*PlayerInfo `protobuf:"bytes,4,rep,name=playerInfos,proto3" json:"playerInfos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurrentPlayer string                 `protobuf:"bytes,5,opt,name=currentPlayer,proto3" json:"currentPlayer,omitempty"`
	OnGoing       bool                   `protobuf:"varint,6,opt,name=onGoing,proto3" json:"onGoing,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Update) GetDrawSet() *HiddenSet {
	if x != nil {
		return x.DrawSet
	}
	return nil
}

func (x *Update) GetFoldSet() *Set {
	if x != nil {
		return x.FoldSet
	}
	return nil
}

func (x *Update) GetHandSet() *Set {
	if x != nil {
		return x.HandSet
	}
	return nil
}

func (x *Update) GetPlayerInfos() map[string]*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

func (x *Update) GetCurrentPlayer() string {
	if x != nil {
		return x.CurrentPlayer
	}
	return ""
}

func (x *Update) GetOnGoing() bool {
	if x != nil {
		return x.OnGoing
	}
	return false
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x72, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07,
	0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x19, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x09, 0x48, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x58, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x53, 0x65, 0x74,
	0x52, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x64, 0x53, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e,
	0x53, 0x65, 0x74, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x53, 0x65, 0x74, 0x73, 0x22,
	0x94, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x48, 0x00, 0x52, 0x04, 0x64, 0x72, 0x61, 0x77, 0x12,
	0x2d, 0x0a, 0x0a, 0x64, 0x72, 0x61, 0x77, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0a, 0x64, 0x72, 0x61, 0x77, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x64, 0x12, 0x1b,
	0x0a, 0x04, 0x66, 0x6f, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46,
	0x6f, 0x6c, 0x64, 0x48, 0x00, 0x52, 0x04, 0x66, 0x6f, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x53, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x53, 0x65, 0x74, 0x48, 0x00, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x65,
	0x74, 0x12, 0x39, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43,
	0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x6c,
	0x61, 0x79, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22,
	0x06, 0x0a, 0x04, 0x44, 0x72, 0x61, 0x77, 0x22, 0x2c, 0x0a, 0x0a, 0x44, 0x72, 0x61, 0x77, 0x46,
	0x6f, 0x6c, 0x64, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x21, 0x0a, 0x04, 0x46, 0x6f, 0x6c, 0x64, 0x12, 0x19, 0x0a,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x25, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79,
	0x53, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22,
	0x8f, 0x01, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x53,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x53,
	0x65, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x23, 0x0a,
	0x0a, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x4f, 0x6e, 0x4c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x0a, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x4f, 0x6e, 0x4c, 0x6f, 0x77, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x4f, 0x6e, 0x4c, 0x6f,
	0x77, 0x22, 0xb7, 0x02, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x07,
	0x64, 0x72, 0x61, 0x77, 0x53, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x07, 0x64, 0x72, 0x61, 0x77, 0x53,
	0x65, 0x74, 0x12, 0x1e, 0x0a, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x53,
	0x65, 0x74, 0x12, 0x1e, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x53,
	0x65, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x6e, 0x47, 0x6f, 0x69, 0x6e, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6f, 0x6e, 0x47, 0x6f, 0x69, 0x6e, 0x67, 0x1a, 0x4b,
	0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x39, 0x0a, 0x06, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x75, 0x62, 0x73, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x73, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x72, 0x74, 0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x70,
	0x61, 0x64, 0x65, 0x73, 0x10, 0x03, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_messages_proto_goTypes = []interface{}{
	(Symbol)(0),            // 0: Symbol
	(*Card)(nil),           // 1: Card
	(*Set)(nil),            // 2: Set
	(*HiddenSet)(nil),      // 3: HiddenSet
	(*PlayerInfo)(nil),     // 4: PlayerInfo
	(*Action)(nil),         // 5: Action
	(*Start)(nil),          // 6: Start
	(*Draw)(nil),           // 7: Draw
	(*DrawFolded)(nil),     // 8: DrawFolded
	(*Fold)(nil),           // 9: Fold
	(*PlaySet)(nil),        // 10: PlaySet
	(*PlaySingleCard)(nil), // 11: PlaySingleCard
	(*Update)(nil),         // 12: Update
	nil,                    // 13: Update.PlayerInfosEntry
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: Card.symbol:type_name -> Symbol
	1,  // 1: Set.cards:type_name -> Card
	3,  // 2: PlayerInfo.handSet:type_name -> HiddenSet
	2,  // 3: PlayerInfo.playedSets:type_name -> Set
	6,  // 4: Action.start:type_name -> Start
	7,  // 5: Action.draw:type_name -> Draw
	8,  // 6: Action.drawFolded:type_name -> DrawFolded
	9,  // 7: Action.fold:type_name -> Fold
	10, // 8: Action.playSet:type_name -> PlaySet
	11, // 9: Action.playSingleCard:type_name -> PlaySingleCard
	1,  // 10: Fold.card:type_name -> Card
	2,  // 11: PlaySet.cards:type_name -> Set
	1,  // 12: PlaySingleCard.card:type_name -> Card
	3,  // 13: Update.drawSet:type_name -> HiddenSet
	2,  // 14: Update.foldSet:type_name -> Set
	2,  // 15: Update.handSet:type_name -> Set
	13, // 16: Update.playerInfos:type_name -> Update.PlayerInfosEntry
	4,  // 17: Update.PlayerInfosEntry.value:type_name -> PlayerInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiddenSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Draw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawFolded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fold); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaySet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaySingleCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_messages_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Action_Start)(nil),
		(*Action_Draw)(nil),
		(*Action_DrawFolded)(nil),
		(*Action_Fold)(nil),
		(*Action_PlaySet)(nil),
		(*Action_PlaySingleCard)(nil),
	}
	file_messages_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
